### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by devinmatte** [mayhewj/greenstalk#1]
I've been looking for a beanstalkd python engine, and yours seems to be the only one with Python 3.5+ support. However I don't really know how to use it due to the lack of documentation. If you could spin up some documentation on how to set up a basic implementation of it I'd greatly appreciate it. Especially because then I could use it, and possibly, contribute

Edit: I've been reading through the source code, and I understand how it works now. However having some documentation would still be very useful

**Comment by mayhewj** [comment]
Accidentally closed the issue there! Sorry.

I've been meaning to get some basic documentation up and running. Here's a basic quickstart for now:

Installation
------------

Greenstalk supports Python 3.5 and later. It's available on the Python Package Index and can be installed by running::

    $ pip3 install greenstalk

Quickstart
----------

The first step is to import the library and create a Client, which immediately connects to ``beanstalkd``:
    
    >>> import greenstalk
    >>> c = greenstalk.Client()

If ``beanstalkd`` isn't running locally on the default port you'll need to specify where it's running:

    >>> c = greenstalk.Client(host='queue.example.com', port=4444)

You can add a job to the queue using `put`:

    >>> c.put('Hello, world!')
    1

The job ID is returned which means that the job was successfully enqueued. We can dequeue a job using reserve` which returns a tuple containing the job ID and job body.

    >>> jid, body = c.reserve()
    >>> jid
    1
    >>> print(body)
    Hello, world!

When you're done with the job, use delete:

    >>> c.delete(jid)

I hope that helps a bit! This library is basically a thin wrapper around the beanstalk protocol and doesn't provide much of any abstraction/DSL on top of it which makes https://github.com/kr/beanstalkd/blob/master/doc/protocol.txt and the tests the best resource if you're interested in learning more.

It's still an immature library with lots of work needed! Thanks for checking it out. Contributions are very welcome!

**Comment by mayhewj** [comment]
Initial documentation is now on Read the Docs: https://greenstalk.readthedocs.io/en/latest/

It's still a work in progress, but should definitely help people get up and running.
