### ISSUE TITLE
Document for binary data

### ISSUE THREAD

**Issue by zhengwx11** [mayhewj/greenstalk#2]
Most of the usage could be inferred via `beanstalkd`. But the encoding control needs more documents.

### sample
It is controled by the `encoding` of `Client.__init__()`. 

When `encoding` is not `None`, the input of `Client.put()` should be `str`, and the output of `Client.reserve()` would be `str` too. Consistent `encoding` for both producer and consumer is neccessary.

When `encoding` is `None`, the input of `Client.put()` should be `bytes`, and the output of `Client.reserve()` would be `bytes` too. Consistent `encoding` (`None`) for both producer and consumer is neccessary.

Behaviours under other settings are undefined.

**Comment by mayhewj** [comment]
Hey @zhengwx11, I'm working on improving the docs and should hopefully have something up soon. I'll definitely make sure to mention this, thank you!

**Comment by mayhewj** [comment]
Added some docs: https://greenstalk.readthedocs.io/en/latest/quickstart.html#body-encoding
